---
title: Merge Synthetic Data
subtitle: Ayush Noori
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
# knitr::opts_knit$set(root.dir = normalizePath(""))
```

# Dependencies

Load requisite packages and define directories. Note that this script uses my personal utilities package `brainstorm`, which can be downloaded via `devtools::install_github("ayushnoori/brainstorm")`.

```{r load-packages, message=FALSE, warning=FALSE}

# data manipulation
library(data.table)
library(purrr)
library(magrittr)

# relative file paths
library(here)

# string manipulation
library(stringr)

# utility functions
library(brainstorm)

```

Note that directories are relative to the R project path.

```{r define-directores}

# set directories
synthea_dir = file.path("synthea")

```

Read files.

```{r read-files}

# generate file list
patient_files = list.files(synthea_dir, include.dirs = F, full.names = T, pattern = ".csv")

# read files
patient_data = map(patient_files, fread)
names(patient_data) = gsub(".csv", "", basename(patient_files), fixed = T)

```
